### ISSUE TITLE
Dust storms.

### ISSUE THREAD

**Issue by yosi90** [Dubwise56/MarsX#24]
I dont know if its intended but, while dust storm is happening:
- Pawns don't clean the equipment.
- I can't prioritize cleaning the equipment.

Even when dust storm fades:
- interiors floor also gets dirty. (not real dirt, just a visual glitch cuz of the dust storm)

**Comment by Dubwise56** [comment]
fixed dust buildup in next update

and you aren't supposed to be able to clean during a dust storm, because its dangerous and pawns can get lost and die, and they are also just wasting time fighting constant dust buildup, but i can allow it so people have the choice to get lost and die if they want to risk it

**Comment by yosi90** [comment]
Last year's alpha allowed it, so I assumed it could be a bug. sorry for bothering.
