### ISSUE TITLE
v1.3 Eva suit dont recharge on the ilav

### ISSUE THREAD

**Issue by yosi90** [Dubwise56/MarsX#38]
if you force the pawns to enter the ilav, the eva suit dont recharge the energy.
edit: They even lose oxigen cuz of the lack of energy.

**Comment by Dubwise56** [comment]
this is a semi bug, while in the ship they use the ships o2 if there is any, and the suit doesn't discharge. but the suits charge capacity is very small and the vanilla self discharge on battery's is still enabled and draining 5watt days constantly which is a heck of a lot on a small battery. so i upped the capacity on the suits, and im patching out vanilla self drain to a % over time instead of a flat rate of watts. and i'll get suit charging inside ships working
